/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import accesoADatos.participanteDAO;
import com.mxrck.autocompleter.TextAutoCompleter;
import java.awt.event.ActionEvent;
import javax.swing.JOptionPane;
import modelo.ParticipanteModel;

/**
 *
 * @author David
 */
public class ventanaActualizar extends javax.swing.JFrame {
 
    /**
     * Creates new form Actualizar
     */
    public ventanaActualizar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        iconoActualizar = new javax.swing.JLabel();
        actualizarD = new javax.swing.JLabel();
        Imagen = new javax.swing.JLabel();
        paneBotones = new javax.swing.JPanel();
        nombreU1 = new javax.swing.JLabel();
        CampoA = new javax.swing.JLabel();
        txtNombreU = new javax.swing.JTextField();
        jcboActualizar = new javax.swing.JComboBox<>();
        botonActualizar = new javax.swing.JButton();
        Actualizado = new javax.swing.JLabel();
        txtActualizado = new javax.swing.JTextField();

        setLocationByPlatform(true);

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconoActualizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconoActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/actualizar (1).png"))); // NOI18N
        Background.add(iconoActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 4, 190, -1));

        actualizarD.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        actualizarD.setForeground(new java.awt.Color(255, 255, 255));
        actualizarD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        actualizarD.setText("Actualizar Datos");
        Background.add(actualizarD, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 490, 130));

        Imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Imagen.jpg"))); // NOI18N
        Background.add(Imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 130));

        paneBotones.setBackground(new java.awt.Color(255, 255, 255));

        nombreU1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        nombreU1.setText("Nombre de Usuario");

        CampoA.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        CampoA.setText("Campo a Actualizar");

        ac = new TextAutoCompleter(txtNombreU);
        ac.addItem("Marlon");
        ac.addItem("Juan");
        ac.addItem("David");
        txtNombreU.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtNombreU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreUActionPerformed(evt);
            }
        });

        jcboActualizar.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jcboActualizar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Correo Electronico", "Celular", "Clave", "Nombre", "Apellido", "Fecha Nacimiento" }));
        jcboActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboActualizarActionPerformed(evt);
            }
        });

        botonActualizar.setBackground(new java.awt.Color(63, 137, 164));
        botonActualizar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        botonActualizar.setForeground(new java.awt.Color(255, 255, 255));
        botonActualizar.setText("Actualizar");
        botonActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarActionPerformed(evt);
            }
        });

        Actualizado.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        Actualizado.setText("Dato a Actualizar");

        txtActualizado.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        javax.swing.GroupLayout paneBotonesLayout = new javax.swing.GroupLayout(paneBotones);
        paneBotones.setLayout(paneBotonesLayout);
        paneBotonesLayout.setHorizontalGroup(
            paneBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneBotonesLayout.createSequentialGroup()
                .addGap(55, 55, Short.MAX_VALUE)
                .addGroup(paneBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(paneBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneBotonesLayout.createSequentialGroup()
                            .addComponent(nombreU1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNombreU, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneBotonesLayout.createSequentialGroup()
                            .addGroup(paneBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(CampoA, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Actualizado, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(paneBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(paneBotonesLayout.createSequentialGroup()
                                    .addGap(33, 33, 33)
                                    .addComponent(jcboActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneBotonesLayout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtActualizado, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(155, 155, 155))
        );
        paneBotonesLayout.setVerticalGroup(
            paneBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreU, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreU1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(paneBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcboActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoA, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(paneBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtActualizado, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Actualizado, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botonActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        Background.add(paneBotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 580, 270));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcboActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcboActualizarActionPerformed

    private void botonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarActionPerformed
        Update(evt);
    }//GEN-LAST:event_botonActualizarActionPerformed

    private void txtNombreUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreUActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaActualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaActualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaActualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaActualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new ventanaActualizar().setVisible(true);
            }
        });
    }
    
    public void autocompletarJtext(){
        
    }
    
    
    public void Update(ActionEvent evt){
        
        if(evt.getSource() == botonActualizar){
            
            String datoJcbo       = (String) jcboActualizar.getSelectedItem();                       
            String datoOutputTxt  = txtNombreU.getText();
            String datoOutputTxt2 = txtActualizado.getText();
            
            if(datoOutputTxt.equals("") || datoOutputTxt2.equals("")){              
                JOptionPane.showMessageDialog(null, "Faltan campos por llenar");
     
            }else{
                
                if(datoJcbo.equals("Correo Electronico")){

                          pModel = new ParticipanteModel();
                          pModel.setPar_email(datoOutputTxt2);
                          pModel.setPar_login(datoOutputTxt);

                          pDAO = new participanteDAO();
                          pDAO.updateEmail(pModel);

                  
                }else if(datoJcbo.equals("Celular")){ 
                    try{
                          pModel = new ParticipanteModel();
                          pModel.setPar_celular(Long.parseLong(datoOutputTxt2));
                          pModel.setPar_login(datoOutputTxt);

                          pDAO = new participanteDAO();
                          pDAO.updateCelular(pModel);
                          
                    }catch(NumberFormatException ex){
        	          JOptionPane.showMessageDialog(null, "No se permiten letras");
    	         }        

                }else if(datoJcbo.equals("Clave")){

                          pModel = new ParticipanteModel();
                          pModel.setPar_clave(datoOutputTxt2);
                          pModel.setPar_login(datoOutputTxt);

                          pDAO = new participanteDAO();
                          pDAO.updateClave(pModel);


                }else if(datoJcbo.equals("Nombre")){

                          pModel = new ParticipanteModel();
                          pModel.setPar_nombre(datoOutputTxt2);
                          pModel.setPar_login(datoOutputTxt);

                          pDAO = new participanteDAO();
                          pDAO.updateNombre(pModel);


                }else if(datoJcbo.equals("Apellido")){

                          pModel = new ParticipanteModel();
                          pModel.setPar_apellido(datoOutputTxt2);
                          pModel.setPar_login(datoOutputTxt);

                          pDAO = new participanteDAO();
                          pDAO.updateApellido(pModel);


                }else if(datoJcbo.equals("Fecha Nacimiento")){

                          pModel = new ParticipanteModel();
                          pModel.setPar_fecha_nto(datoOutputTxt2);
                          pModel.setPar_login(datoOutputTxt);

                          pDAO = new participanteDAO();
                          pDAO.updateFecha(pModel);

                }
                
              txtActualizado.setText("");
              jcboActualizar.setSelectedItem("Correo Electronico");
            }    
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Actualizado;
    private javax.swing.JPanel Background;
    private javax.swing.JLabel CampoA;
    private javax.swing.JLabel Imagen;
    private javax.swing.JLabel actualizarD;
    public javax.swing.JButton botonActualizar;
    private javax.swing.JLabel iconoActualizar;
    public javax.swing.JComboBox<String> jcboActualizar;
    private javax.swing.JLabel nombreU1;
    private javax.swing.JPanel paneBotones;
    public javax.swing.JTextField txtActualizado;
    public javax.swing.JTextField txtNombreU;
    // End of variables declaration//GEN-END:variables
    public participanteDAO pDAO;
    public ParticipanteModel pModel;
    private TextAutoCompleter ac;

}
